<?php

namespace BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByCategory($slug)
    {
    	return $this->getEntityManager()
        	->createQuery(
                'SELECT p FROM BlogBundle:Post p
                JOIN p.category c
                WHERE c.slug = :slug
                ORDER BY p.id DESC'
            )
            ->setParameter('slug', $slug)
            ->getResult();
    }
}
